import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getShipmentReport } from '../services/insightsApi';
import LoadingAnimation from '../components/LoadingAnimation';
import DeliverySummary from '../components/DeliverySummary';
import PerformanceCard from '../components/PerformanceCard';
import JourneyEvents from '../components/JourneyEvents';
import RecommendationCard from '../components/RecommendationCard';
import ActionButtons from '../components/ActionButtons';

const LogisticsReportPage = () => {
  const { shipmentId } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchReport();
  }, [shipmentId]);

  const fetchReport = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await getShipmentReport(shipmentId);
      // Simulate slightly longer loading for the AI animation
      setTimeout(() => {
        setReport(data);
        setLoading(false);
      }, 4000); // 4 seconds
    } catch (err) {
      console.error(err);
      if (err.response?.status === 404) {
        setError('Shipment not found.');
      } else {
        setError('Unable to connect to server.');
      }
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="app-container">
        <nav className="navbar">
          <div className="nav-brand">
            <span className="logo-icon">📊</span>
            <div>
              <h1>SupplySync AI</h1>
              <span className="nav-sub">Logistics Insights Agent</span>
            </div>
          </div>
          <div className="ai-badge">Agent Active</div>
        </nav>
        <main>
          <LoadingAnimation />
        </main>
      </div>
    );
  }

  if (error) {
    return (
      <div className="app-container">
        <nav className="navbar">
          <div className="nav-brand">
            <span className="logo-icon">📊</span>
            <div>
              <h1>SupplySync AI</h1>
              <span className="nav-sub">Logistics Insights Agent</span>
            </div>
          </div>
        </nav>
        <main>
          <div className="state-message">
            <span className="state-message-icon">⚠️</span>
            <h3>Error Loading Report</h3>
            <p>{error}</p>
            <button className="btn btn-secondary mt-3" onClick={() => navigate('/')}>
              ← Back to Shipments
            </button>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="app-container">
      <nav className="navbar">
        <div className="nav-brand">
          <span className="logo-icon">📊</span>
          <div>
            <h1>SupplySync AI</h1>
            <span className="nav-sub">Logistics Insights Agent</span>
          </div>
        </div>
        <div className="nav-shipment-info">
          <span className="nav-sub">Analyzing</span>
          <span style={{ fontWeight: 600, fontSize: '0.85rem' }}>{report.shipmentId}</span>
        </div>
      </nav>

      <main className="report-page">
        <div className="report-header">
          <h2>Logistics Performance Report</h2>
          <p>Generated by SupplySync AI based on actual simulation data</p>
        </div>

        <DeliverySummary report={report} />
        <PerformanceCard report={report} />
        <JourneyEvents events={report.simulationEvents} />
        <RecommendationCard recommendations={report.recommendations} />
        <ActionButtons onRefresh={fetchReport} report={report} />
      </main>
    </div>
  );
};

export default LogisticsReportPage;
